config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcome#index'

  resources :pannellos
  resources :operas

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_attached_file :image, 
  styles: { 
    normal: "1024x1024>", 
    medium: "300x300>", 
    thumb: "100x100>",
    big: "600x600>"
  },  
  convert_options: {
    normal: '-quality 90 -strip',
    medium: '-quality 80 -strip',
    thumb: '-quality 60 -strip',
    big: '-quality 80 -strip'
  }
  belongs_to :opera
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :image, :opera_id, presence: true
end

app/models/opera.rb
class Opera < ActiveRecord::Base
  has_attached_file :image, styles: { 
    normal: "1024x1024>", 
    medium: "300x300>", 
    thumb: "100x100>",
    big: "600x600>",
    quad2: "300x300#"
  },  
  convert_options: {
    normal: '-quality 90 -strip',
    medium: '-quality 80 -strip',
    thumb: '-quality 60 -strip',
    big: '-quality 80 -strip',
    quad2: '-quality 80 -strip'
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :archive_index, :image, :pannello, presence: true
  belongs_to :pannello
  has_many :details

end

app/models/pannello.rb
class Pannello < ActiveRecord::Base
  has_attached_file :image, styles: { 
    normal: "1024x1024>",
    big: "600x600>",
    medium: "300x300>", 
    thumb: "100x100>" 
  },  
  convert_options: {
    normal: '-quality 90 -strip',
    medium: '-quality 80 -strip',
    thumb: '-quality 60 -strip',
    big: '-quality 80 -strip'
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :image
  has_many :operas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :random_image_cover
  def random_image_cover
     @detail = Detail.where(cover: true).limit(5).order("RANDOM()").first
  end
end

app/controllers/operas_controller.rb
class OperasController < ApplicationController
  def index
    @operas = Opera.all.order(:archive_index)
  end
  def show
    @opera = Opera.find params[:id]
  end
end

app/controllers/pannellos_controller.rb
class PannellosController < ApplicationController
  def index
    @pannellos = Pannello.all
  end
  def show
    @pannello = Pannello.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @pannellos = Pannello.all
    @operas = Opera.all
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title GataAsta
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    = javascript_include_tag 'application'
    %meta{name:"viewport", content:"width=device-width, initial-scale=1.0"}
  %body
    .container-fluid
      #cover.row{style:"background-color: white;  background-image: url(#{@detail.image.url(:normal)}); background-size: cover; background-position: center"}
        .col-sm-12
          .pull-left
            %strong
              = link_to 'Gatarigole', root_path, style: "padding: 20px; margin-left: -20px; display: block; color: white"
          .pull-right
            %div(style="padding: 20px; display: block")
              %strong= link_to 'Pannelli', pannellos_path, style: "padding: 20px; color: white"
              %strong= link_to 'Asta', operas_path, style: "padding: 20px; color: white; margin-right: -20px"
      
      .row
        .col-sm-12(style="padding-top: 20px")
          = yield
    

app/views/operas/index.haml
- @operas.each do |p|
  .col-sm-3
    = link_to(image_tag(p.image.url(:quad2), class:'img-responsive'), p)
    = p.archive_index

app/views/operas/show.haml
%p(style="margin-bottom: 20px")
  = link_to 'Pannelli', pannellos_path
  = '/'
  = link_to "Pannello #{@opera.pannello.name}", @opera.pannello
  = '/'
  = 'Opera'

.row
  .col-sm-12
    = image_tag @opera.image.url(:normal), class: 'img-responsive'
    %br
    Indice di archivio 
    = @opera.archive_index

app/views/pannellos/index.haml
- @pannellos.each do |p|
  = link_to(image_tag(p.image.url(:medium)), p)

app/views/pannellos/show.haml
%p(style="margin-bottom: 20px")
  = link_to 'Pannelli', pannellos_path
  = '/'
  = "Pannello #{@pannello.name}"
  
.row
  .col-sm-2
    = image_tag(@pannello.image.url(:normal), class: 'img-responsive')
  .col-sm-10
    #container-packery
      .grid-sizer
      - @pannello.operas.order(:archive_index).each do |o|
        .item
          = link_to(image_tag(o.image.url(:big)), o)
          .pallino= o.archive_index


:css
  .item{
    position: relative;
    display: block;
  }
  .pallino {
    position: absolute;
    top: 0;
    font-size: 20px;
    color: #fff;
    padding: 10px;
    margin: 10px;;
    border-radius: 100px;
    background-color: #337ab7;
    width: 50px; 
    text-align: center
  }

app/views/welcome/index.haml
:javascript
  
  doFullScreen()